// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sysconfig.proto

#ifndef PROTOBUF_INCLUDED_sysconfig_2eproto
#define PROTOBUF_INCLUDED_sysconfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_sysconfig_2eproto 

namespace protobuf_sysconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_sysconfig_2eproto
class SysConfig;
class SysConfigDefaultTypeInternal;
extern SysConfigDefaultTypeInternal _SysConfig_default_instance_;
namespace google {
namespace protobuf {
template<> ::SysConfig* Arena::CreateMaybeMessage<::SysConfig>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class SysConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SysConfig) */ {
 public:
  SysConfig();
  virtual ~SysConfig();

  SysConfig(const SysConfig& from);

  inline SysConfig& operator=(const SysConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SysConfig(SysConfig&& from) noexcept
    : SysConfig() {
    *this = ::std::move(from);
  }

  inline SysConfig& operator=(SysConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SysConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SysConfig* internal_default_instance() {
    return reinterpret_cast<const SysConfig*>(
               &_SysConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SysConfig* other);
  friend void swap(SysConfig& a, SysConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SysConfig* New() const final {
    return CreateMaybeMessage<SysConfig>(NULL);
  }

  SysConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SysConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SysConfig& from);
  void MergeFrom(const SysConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SysConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ComponentID = 1;
  void clear_componentid();
  static const int kComponentIDFieldNumber = 1;
  const ::std::string& componentid() const;
  void set_componentid(const ::std::string& value);
  #if LANG_CXX11
  void set_componentid(::std::string&& value);
  #endif
  void set_componentid(const char* value);
  void set_componentid(const char* value, size_t size);
  ::std::string* mutable_componentid();
  ::std::string* release_componentid();
  void set_allocated_componentid(::std::string* componentid);

  // int32 DeviceStatusInterval = 2;
  void clear_devicestatusinterval();
  static const int kDeviceStatusIntervalFieldNumber = 2;
  ::google::protobuf::int32 devicestatusinterval() const;
  void set_devicestatusinterval(::google::protobuf::int32 value);

  // int32 DataInterval = 3;
  void clear_datainterval();
  static const int kDataIntervalFieldNumber = 3;
  ::google::protobuf::int32 datainterval() const;
  void set_datainterval(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SysConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr componentid_;
  ::google::protobuf::int32 devicestatusinterval_;
  ::google::protobuf::int32 datainterval_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_sysconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SysConfig

// string ComponentID = 1;
inline void SysConfig::clear_componentid() {
  componentid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SysConfig::componentid() const {
  // @@protoc_insertion_point(field_get:SysConfig.ComponentID)
  return componentid_.GetNoArena();
}
inline void SysConfig::set_componentid(const ::std::string& value) {
  
  componentid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SysConfig.ComponentID)
}
#if LANG_CXX11
inline void SysConfig::set_componentid(::std::string&& value) {
  
  componentid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:SysConfig.ComponentID)
}
#endif
inline void SysConfig::set_componentid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  componentid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SysConfig.ComponentID)
}
inline void SysConfig::set_componentid(const char* value, size_t size) {
  
  componentid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SysConfig.ComponentID)
}
inline ::std::string* SysConfig::mutable_componentid() {
  
  // @@protoc_insertion_point(field_mutable:SysConfig.ComponentID)
  return componentid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SysConfig::release_componentid() {
  // @@protoc_insertion_point(field_release:SysConfig.ComponentID)
  
  return componentid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SysConfig::set_allocated_componentid(::std::string* componentid) {
  if (componentid != NULL) {
    
  } else {
    
  }
  componentid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), componentid);
  // @@protoc_insertion_point(field_set_allocated:SysConfig.ComponentID)
}

// int32 DeviceStatusInterval = 2;
inline void SysConfig::clear_devicestatusinterval() {
  devicestatusinterval_ = 0;
}
inline ::google::protobuf::int32 SysConfig::devicestatusinterval() const {
  // @@protoc_insertion_point(field_get:SysConfig.DeviceStatusInterval)
  return devicestatusinterval_;
}
inline void SysConfig::set_devicestatusinterval(::google::protobuf::int32 value) {
  
  devicestatusinterval_ = value;
  // @@protoc_insertion_point(field_set:SysConfig.DeviceStatusInterval)
}

// int32 DataInterval = 3;
inline void SysConfig::clear_datainterval() {
  datainterval_ = 0;
}
inline ::google::protobuf::int32 SysConfig::datainterval() const {
  // @@protoc_insertion_point(field_get:SysConfig.DataInterval)
  return datainterval_;
}
inline void SysConfig::set_datainterval(::google::protobuf::int32 value) {
  
  datainterval_ = value;
  // @@protoc_insertion_point(field_set:SysConfig.DataInterval)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_sysconfig_2eproto
