// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fantimingconfig.proto

#include "fantimingconfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class FanTimingConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FanTimingConfig>
      _instance;
} _FanTimingConfig_default_instance_;
namespace protobuf_fantimingconfig_2eproto {
static void InitDefaultsFanTimingConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_FanTimingConfig_default_instance_;
    new (ptr) ::FanTimingConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::FanTimingConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_FanTimingConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFanTimingConfig}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_FanTimingConfig.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FanTimingConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FanTimingConfig, active_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FanTimingConfig, basetime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FanTimingConfig, endtime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FanTimingConfig, interval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FanTimingConfig, openmin_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::FanTimingConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_FanTimingConfig_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "fantimingconfig.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025fantimingconfig.proto\"g\n\017FanTimingConf"
      "ig\022\016\n\006active\030\001 \001(\t\022\020\n\010baseTime\030\002 \001(\t\022\017\n\007"
      "endTime\030\003 \001(\t\022\020\n\010interval\030\004 \001(\005\022\017\n\007openM"
      "in\030\005 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 136);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "fantimingconfig.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_fantimingconfig_2eproto

// ===================================================================

void FanTimingConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FanTimingConfig::kActiveFieldNumber;
const int FanTimingConfig::kBaseTimeFieldNumber;
const int FanTimingConfig::kEndTimeFieldNumber;
const int FanTimingConfig::kIntervalFieldNumber;
const int FanTimingConfig::kOpenMinFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FanTimingConfig::FanTimingConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_fantimingconfig_2eproto::scc_info_FanTimingConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:FanTimingConfig)
}
FanTimingConfig::FanTimingConfig(const FanTimingConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  active_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.active().size() > 0) {
    active_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.active_);
  }
  basetime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.basetime().size() > 0) {
    basetime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.basetime_);
  }
  endtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.endtime().size() > 0) {
    endtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endtime_);
  }
  ::memcpy(&interval_, &from.interval_,
    static_cast<size_t>(reinterpret_cast<char*>(&openmin_) -
    reinterpret_cast<char*>(&interval_)) + sizeof(openmin_));
  // @@protoc_insertion_point(copy_constructor:FanTimingConfig)
}

void FanTimingConfig::SharedCtor() {
  active_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  basetime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&interval_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&openmin_) -
      reinterpret_cast<char*>(&interval_)) + sizeof(openmin_));
}

FanTimingConfig::~FanTimingConfig() {
  // @@protoc_insertion_point(destructor:FanTimingConfig)
  SharedDtor();
}

void FanTimingConfig::SharedDtor() {
  active_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  basetime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endtime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FanTimingConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* FanTimingConfig::descriptor() {
  ::protobuf_fantimingconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fantimingconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FanTimingConfig& FanTimingConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_fantimingconfig_2eproto::scc_info_FanTimingConfig.base);
  return *internal_default_instance();
}


void FanTimingConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:FanTimingConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  active_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  basetime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&interval_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&openmin_) -
      reinterpret_cast<char*>(&interval_)) + sizeof(openmin_));
  _internal_metadata_.Clear();
}

bool FanTimingConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FanTimingConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string active = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_active()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->active().data(), static_cast<int>(this->active().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "FanTimingConfig.active"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string baseTime = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_basetime()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->basetime().data(), static_cast<int>(this->basetime().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "FanTimingConfig.baseTime"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string endTime = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_endtime()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->endtime().data(), static_cast<int>(this->endtime().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "FanTimingConfig.endTime"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 interval = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &interval_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 openMin = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &openmin_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FanTimingConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FanTimingConfig)
  return false;
#undef DO_
}

void FanTimingConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FanTimingConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string active = 1;
  if (this->active().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->active().data(), static_cast<int>(this->active().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FanTimingConfig.active");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->active(), output);
  }

  // string baseTime = 2;
  if (this->basetime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->basetime().data(), static_cast<int>(this->basetime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FanTimingConfig.baseTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->basetime(), output);
  }

  // string endTime = 3;
  if (this->endtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endtime().data(), static_cast<int>(this->endtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FanTimingConfig.endTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->endtime(), output);
  }

  // int32 interval = 4;
  if (this->interval() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->interval(), output);
  }

  // int32 openMin = 5;
  if (this->openmin() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->openmin(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:FanTimingConfig)
}

::google::protobuf::uint8* FanTimingConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:FanTimingConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string active = 1;
  if (this->active().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->active().data(), static_cast<int>(this->active().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FanTimingConfig.active");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->active(), target);
  }

  // string baseTime = 2;
  if (this->basetime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->basetime().data(), static_cast<int>(this->basetime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FanTimingConfig.baseTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->basetime(), target);
  }

  // string endTime = 3;
  if (this->endtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endtime().data(), static_cast<int>(this->endtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FanTimingConfig.endTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->endtime(), target);
  }

  // int32 interval = 4;
  if (this->interval() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->interval(), target);
  }

  // int32 openMin = 5;
  if (this->openmin() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->openmin(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FanTimingConfig)
  return target;
}

size_t FanTimingConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FanTimingConfig)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string active = 1;
  if (this->active().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->active());
  }

  // string baseTime = 2;
  if (this->basetime().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->basetime());
  }

  // string endTime = 3;
  if (this->endtime().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->endtime());
  }

  // int32 interval = 4;
  if (this->interval() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->interval());
  }

  // int32 openMin = 5;
  if (this->openmin() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->openmin());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FanTimingConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FanTimingConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const FanTimingConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FanTimingConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FanTimingConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FanTimingConfig)
    MergeFrom(*source);
  }
}

void FanTimingConfig::MergeFrom(const FanTimingConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FanTimingConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.active().size() > 0) {

    active_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.active_);
  }
  if (from.basetime().size() > 0) {

    basetime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.basetime_);
  }
  if (from.endtime().size() > 0) {

    endtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endtime_);
  }
  if (from.interval() != 0) {
    set_interval(from.interval());
  }
  if (from.openmin() != 0) {
    set_openmin(from.openmin());
  }
}

void FanTimingConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FanTimingConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FanTimingConfig::CopyFrom(const FanTimingConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FanTimingConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FanTimingConfig::IsInitialized() const {
  return true;
}

void FanTimingConfig::Swap(FanTimingConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FanTimingConfig::InternalSwap(FanTimingConfig* other) {
  using std::swap;
  active_.Swap(&other->active_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  basetime_.Swap(&other->basetime_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  endtime_.Swap(&other->endtime_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(interval_, other->interval_);
  swap(openmin_, other->openmin_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata FanTimingConfig::GetMetadata() const {
  protobuf_fantimingconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fantimingconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::FanTimingConfig* Arena::CreateMaybeMessage< ::FanTimingConfig >(Arena* arena) {
  return Arena::CreateInternal< ::FanTimingConfig >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
